export type WarehouseType = 'main' | 'sales';
export type WarehouseStatus = 'active' | 'inactive';

export interface Warehouse {
  id: string;
  name: string;
  code: string;
  type: WarehouseType;
  branches: string[];
  address: string;
  stock: number;
  status: WarehouseStatus;
  managerId: string | null;
  manager: { id: string; firstName: string; lastName: string } | null;
  createdAt: string;
  updatedAt: string;
}

// The code is generated by the backend, so it's not part of the payload.
export interface WarehousePayload {
  name: string;
  type: WarehouseType;
  branches: string[];
  address: string;
  stock: number;
  status: WarehouseStatus;
  managerId: string | null;
}

// An HR employee with the manager role in WMS, offered in the Manager dropdown.
export interface ManagerOption {
  id: string;
  name: string;
}
